// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onBodytempChange();
void onEcgValueChange();
void onHumidityChange();
void onIrValueChange();
void onRedValueChange();
void onTemperatureChange();

float bodytemp;
float ecgValue;
float humidity;
float irValue;
float redValue;
float temperature;

void initProperties(){

  ArduinoCloud.addProperty(bodytemp, READWRITE, 1 * SECONDS, onBodytempChange);
  ArduinoCloud.addProperty(ecgValue, READWRITE, ON_CHANGE, onEcgValueChange, 1);
  ArduinoCloud.addProperty(humidity, READWRITE, 1 * SECONDS, onHumidityChange);
  ArduinoCloud.addProperty(irValue, READWRITE, 1 * SECONDS, onIrValueChange);
  ArduinoCloud.addProperty(redValue, READWRITE, 1 * SECONDS, onRedValueChange);
  ArduinoCloud.addProperty(temperature, READWRITE, 1 * SECONDS, onTemperatureChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
